<option value="  " selected>Selecciona un país</option>
<option value="Afganistán">🇦🇫 Afganistán</option>
<option value="Albania">🇦🇱 Albania</option>
<option value="Argelia">🇩🇿 Argelia</option>
<option value="Samoa Americana">🇦🇸 Samoa Americana</option>
<option value="Andorra">🇦🇩 Andorra</option>
<option value="Angola">🇦🇴 Angola</option>
<option value="Anguila">🇦🇮 Anguila</option>
<option value="Antártida">🇦🇶 Antártida</option>
<option value="Antigua y Barbuda">🇦🇬 Antigua y Barbuda</option>
<option value="Argentina">🇦🇷 Argentina</option>
<option value="Armenia">🇦🇲 Armenia</option>
<option value="Aruba">🇦🇼 Aruba</option>
<option value="Australia">🇦🇺 Australia</option>
<option value="Austria">🇦🇹 Austria</option>
<option value="Azerbaiyán">🇦🇿 Azerbaiyán</option>
<option value="Bahamas">🇧🇸 Bahamas</option>
<option value="Baréin">🇧🇭 Baréin</option>
<option value="Bangladesh">🇧🇩 Bangladesh</option>
<option value="Barbados">🇧🇧 Barbados</option>
<option value="Bielorrusia">🇧🇾 Bielorrusia</option>
<option value="Bélgica">🇧🇪 Bélgica</option>
<option value="Belice">🇧🇿 Belice</option>
<option value="Benín">🇧🇯 Benín</option>
<option value="Bermudas">🇧🇲 Bermudas</option>
<option value="Bután">🇧🇹 Bután</option>
<option value="Bolivia">🇧🇴 Bolivia</option>
<option value="Bosnia y Herzegovina">🇧🇦 Bosnia y Herzegovina</option>
<option value="Botsuana">🇧🇼 Botsuana</option>
<option value="Brasil">🇧🇷 Brasil</option>
<option value="Territorio Británico del Océano Índico"
	>🇮🇴 Territorio Británico del Océano Índico</option
>
<option value="Brunéi">🇧🇳 Brunéi</option>
<option value="Bulgaria">🇧🇬 Bulgaria</option>
<option value="Burkina Faso">🇧🇫 Burkina Faso</option>
<option value="Burundi">🇧🇮 Burundi</option>
<option value="Camboya">🇰🇭 Camboya</option>
<option value="Camerún">🇨🇲 Camerún</option>
<option value="Canadá">🇨🇦 Canadá</option>
<option value="Cabo Verde">🇨🇻 Cabo Verde</option>
<option value="Islas Caimán">🇰🇾 Islas Caimán</option>
<option value="República Centroafricana">🇨🇫 República Centroafricana</option>
<option value="Chad">🇹🇩 Chad</option>
<option value="Chile">🇨🇱 Chile</option>
<option value="China">🇨🇳 China</option>
<option value="Isla de Navidad">🇨🇽 Isla de Navidad</option>
<option value="Islas Cocos">🇨🇨 Islas Cocos</option>
<option value="Colombia">🇨🇴 Colombia</option>
<option value="Comoras">🇰🇲 Comoras</option>
<option value="Congo">🇨🇬 Congo</option>
<option value="República Democrática del Congo">🇨🇩 República Democrática del Congo</option>
<option value="Islas Cook">🇨🇰 Islas Cook</option>
<option value="Costa Rica">🇨🇷 Costa Rica</option>
<option value="Costa de Marfil">🇨🇮 Costa de Marfil</option>
<option value="Croacia">🇭🇷 Croacia</option>
<option value="Cuba">🇨🇺 Cuba</option>
<option value="Chipre">🇨🇾 Chipre</option>
<option value="República Checa">🇨🇿 República Checa</option>
<option value="Dinamarca">🇩🇰 Dinamarca</option>
<option value="Yibuti">🇩🇯 Yibuti</option>
<option value="Dominica">🇩🇲 Dominica</option>
<option value="República Dominicana">🇩🇴 República Dominicana</option>
<option value="Timor Oriental">🇹🇱 Timor Oriental</option>
<option value="Ecuador">🇪🇨 Ecuador</option>
<option value="Egipto">🇪🇬 Egipto</option>
<option value="El Salvador">🇸🇻 El Salvador</option>
<option value="Guinea Ecuatorial">🇬🇶 Guinea Ecuatorial</option>
<option value="Eritrea">🇪🇷 Eritrea</option>
<option value="Estonia">🇪🇪 Estonia</option>
<option value="Etiopía">🇪🇹 Etiopía</option>
<option value="Islas Malvinas">🇫🇰 Islas Malvinas</option>
<option value="Islas Feroe">🇫🇴 Islas Feroe</option>
<option value="Fiyi">🇫🇯 Fiyi</option>
<option value="Finlandia">🇫🇮 Finlandia</option>
<option value="Francia">🇫🇷 Francia</option>
<option value="Guayana Francesa">🇬🇫 Guayana Francesa</option>
<option value="Polinesia Francesa">🇵🇫 Polinesia Francesa</option>
<option value="Territorios Franceses del Sur">🇹🇫 Territorios Franceses del Sur</option>
<option value="Gabón">🇬🇦 Gabón</option>
<option value="Gambia">🇬🇲 Gambia</option>
<option value="Georgia">🇬🇪 Georgia</option>
<option value="Alemania">🇩🇪 Alemania</option>
<option value="Ghana">🇬🇭 Ghana</option>
<option value="Gibraltar">🇬🇮 Gibraltar</option>
<option value="Grecia">🇬🇷 Grecia</option>
<option value="Groenlandia">🇬🇱 Groenlandia</option>
<option value="Granada">🇬🇩 Granada</option>
<option value="Guadalupe">🇬🇵 Guadalupe</option>
<option value="Guam">🇬🇺 Guam</option>
<option value="Guatemala">🇬🇹 Guatemala</option>
<option value="Guinea">🇬🇳 Guinea</option>
<option value="Guinea-Bissau">🇬🇼 Guinea-Bissau</option>
<option value="Guyana">🇬🇾 Guyana</option>
<option value="Haití">🇭🇹 Haití</option>
<option value="Islas Heard y McDonald">🇭🇲 Islas Heard y McDonald</option>
<option value="Ciudad del Vaticano">🇻🇦 Ciudad del Vaticano</option>
<option value="Honduras">🇭🇳 Honduras</option>
<option value="Hong Kong">🇭🇰 Hong Kong</option>
<option value="Hungría">🇭🇺 Hungría</option>
<option value="Islandia">🇮🇸 Islandia</option>
<option value="India">🇮🇳 India</option>
<option value="Indonesia">🇮🇩 Indonesia</option>
<option value="Irán">🇮🇷 Irán</option>
<option value="Irak">🇮🇶 Irak</option>
<option value="Irlanda">🇮🇪 Irlanda</option>
<option value="Israel">🇮🇱 Israel</option>
<option value="Italia">🇮🇹 Italia</option>
<option value="Jamaica">🇯🇲 Jamaica</option>
<option value="Japón">🇯🇵 Japón</option>
<option value="Jordania">🇯🇴 Jordania</option>
<option value="Kazajistán">🇰🇿 Kazajistán</option>
<option value="Kenia">🇰🇪 Kenia</option>
<option value="Kiribati">🇰🇮 Kiribati</option>
<option value="Corea del Norte">🇰🇵 Corea del Norte</option>
<option value="Corea del Sur">🇰🇷 Corea del Sur</option>
<option value="Kuwait">🇰🇼 Kuwait</option>
<option value="Kirguistán">🇰🇬 Kirguistán</option>
<option value="Laos">🇱🇦 Laos</option>
<option value="Letonia">🇱🇻 Letonia</option>
<option value="Líbano">🇱🇧 Líbano</option>
<option value="Lesoto">🇱🇸 Lesoto</option>
<option value="Liberia">🇱🇷 Liberia</option>
<option value="Libia">🇱🇾 Libia</option>
<option value="Liechtenstein">🇱🇮 Liechtenstein</option>
<option value="Lituania">🇱🇹 Lituania</option>
<option value="Luxemburgo">🇱🇺 Luxemburgo</option>
<option value="Macao">🇲🇴 Macao</option>
<option value="Macedonia">🇲🇰 Macedonia</option>
<option value="Madagascar">🇲🇬 Madagascar</option>
<option value="Malaui">🇲🇼 Malaui</option>
<option value="Malasia">🇲🇾 Malasia</option>
<option value="Maldivas">🇲🇻 Maldivas</option>
<option value="Mali">🇲🇱 Mali</option>
<option value="Malta">🇲🇹 Malta</option>
<option value="Islas Marshall">🇲🇭 Islas Marshall</option>
<option value="Martinica">🇲🇶 Martinica</option>
<option value="Mauritania">🇲🇷 Mauritania</option>
<option value="Mauricio">🇲🇺 Mauricio</option>
<option value="Mayotte">🇾🇹 Mayotte</option>
<option value="México">🇲🇽 México</option>
<option value="Micronesia">🇫🇲 Micronesia</option>
<option value="Moldavia">🇲🇩 Moldavia</option>
<option value="Mónaco">🇲🇨 Mónaco</option>
<option value="Mongolia">🇲🇳 Mongolia</option>
<option value="Montserrat">🇲🇸 Montserrat</option>
<option value="Marruecos">🇲🇦 Marruecos</option>
<option value="Mozambique">🇲🇿 Mozambique</option>
<option value="Birmania">🇲🇲 Birmania</option>
<option value="Namibia">🇳🇦 Namibia</option>
<option value="Nauru">🇳🇷 Nauru</option>
<option value="Nepal">🇳🇵 Nepal</option>
<option value="Países Bajos">🇳🇱 Países Bajos</option>
<option value="Antillas Neerlandesas">🇦🇳 Antillas Neerlandesas</option>
<option value="Nueva Caledonia">🇳🇨 Nueva Caledonia</option>
<option value="Nueva Zelanda">🇳🇿 Nueva Zelanda</option>
<option value="Nicaragua">🇳🇮 Nicaragua</option>
<option value="Níger">🇳🇪 Níger</option>
<option value="Nigeria">🇳🇬 Nigeria</option>
<option value="Niue">🇳🇺 Niue</option>
<option value="Isla Norfolk">🇳🇫 Isla Norfolk</option>
<option value="Islas Marianas del Norte">🇲🇵 Islas Marianas del Norte</option>
<option value="Noruega">🇳🇴 Noruega</option>
<option value="Omán">🇴🇲 Omán</option>
<option value="Pakistán">🇵🇰 Pakistán</option>
<option value="Palaos">🇵🇼 Palaos</option>
<option value="Panamá">🇵🇦 Panamá</option>
<option value="Papúa Nueva Guinea">🇵🇬 Papúa Nueva Guinea</option>
<option value="Paraguay">🇵🇾 Paraguay</option>
<option value="Perú">🇵🇪 Perú</option>
<option value="Filipinas">🇵🇭 Filipinas</option>
<option value="Pitcairn">🇵🇳 Pitcairn</option>
<option value="Polonia">🇵🇱 Polonia</option>
<option value="Portugal">🇵🇹 Portugal</option>
<option value="Puerto Rico">🇵🇷 Puerto Rico</option>
<option value="Catar">🇶🇦 Catar</option>
<option value="Reunión">🇷🇪 Reunión</option>
<option value="Rumania">🇷🇴 Rumania</option>
<option value="Rusia">🇷🇺 Rusia</option>
<option value="Ruanda">🇷🇼 Ruanda</option>
<option value="San Cristóbal y Nieves">🇰🇳 San Cristóbal y Nieves</option>
<option value="Santa Lucía">🇱🇨 Santa Lucía</option>
<option value="San Vicente y las Granadinas">🇻🇨 San Vicente y las Granadinas</option>
<option value="Samoa">🇼🇸 Samoa</option>
<option value="San Marino">🇸🇲 San Marino</option>
<option value="Santo Tomé y Príncipe">🇸🇹 Santo Tomé y Príncipe</option>
<option value="Arabia Saudí">🇸🇦 Arabia Saudí</option>
<option value="Senegal">🇸🇳 Senegal</option>
<option value="Seychelles">🇸🇨 Seychelles</option>
<option value="Sierra Leona">🇸🇱 Sierra Leona</option>
<option value="Singapur">🇸🇬 Singapur</option>
<option value="Eslovaquia">🇸🇰 Eslovaquia</option>
<option value="Eslovenia">🇸🇮 Eslovenia</option>
<option value="Islas Salomón">🇸🇧 Islas Salomón</option>
<option value="Somalia">🇸🇴 Somalia</option>
<option value="Sudáfrica">🇿🇦 Sudáfrica</option>
<option value="Georgia del Sur y las Islas Sandwich del Sur"
	>🇬🇸 Georgia del Sur y las Islas Sandwich del Sur</option
>
<option value="España">🇪🇸 España</option>
<option value="Sri Lanka">🇱🇰 Sri Lanka</option>
<option value="Santa Elena, Ascensión y Tristán de Acuña"
	>🇸🇭 Santa Elena, Ascensión y Tristán de Acuña</option
>
<option value="San Pedro y Miquelón">🇵🇲 San Pedro y Miquelón</option>
<option value="Sudán">🇸🇩 Sudán</option>
<option value="Surinam">🇸🇷 Surinam</option>
<option value="Svalbard y Jan Mayen">🇸🇯 Svalbard y Jan Mayen</option>
<option value="Suazilandia">🇸🇿 Suazilandia</option>
<option value="Suecia">🇸🇪 Suecia</option>
<option value="Suiza">🇨🇭 Suiza</option>
<option value="Siria">🇸🇾 Siria</option>
<option value="Taiwán">🇹🇼 Taiwán</option>
<option value="Tayikistán">🇹🇯 Tayikistán</option>
<option value="Tanzania">🇹🇿 Tanzania</option>
<option value="Tailandia">🇹🇭 Tailandia</option>
<option value="Togo">🇹🇬 Togo</option>
<option value="Tokelau">🇹🇰 Tokelau</option>
<option value="Tonga">🇹🇴 Tonga</option>
<option value="Trinidad y Tobago">🇹🇹 Trinidad y Tobago</option>
<option value="Túnez">🇹🇳 Túnez</option>
<option value="Turquía">🇹🇷 Turquía</option>
<option value="Turkmenistán">🇹🇲 Turkmenistán</option>
<option value="Islas Turcas y Caicos">🇹🇨 Islas Turcas y Caicos</option>
<option value="Tuvalu">🇹🇻 Tuvalu</option>
<option value="Uganda">🇺🇬 Uganda</option>
<option value="Ucrania">🇺🇦 Ucrania</option>
<option value="Emiratos Árabes Unidos">🇦🇪 Emiratos Árabes Unidos</option>
<option value="Reino Unido">🇬🇧 Reino Unido</option>
<option value="Estados Unidos">🇺🇸 Estados Unidos</option>
<option value="Islas menores alejadas de los Estados Unidos"
	>🇺🇲 Islas menores alejadas de los Estados Unidos</option
>
<option value="Uruguay">🇺🇾 Uruguay</option>
<option value="Uzbekistán">🇺🇿 Uzbekistán</option>
<option value="Vanuatu">🇻🇺 Vanuatu</option>
<option value="Venezuela">🇻🇪 Venezuela</option>
<option value="Vietnam">🇻🇳 Vietnam</option>
<option value="Islas Vírgenes Británicas">🇻🇬 Islas Vírgenes Británicas</option>
<option value="Islas Vírgenes de los Estados Unidos">🇻🇮 Islas Vírgenes de los Estados Unidos</option
>
<option value="Wallis y Futuna">🇼🇫 Wallis y Futuna</option>
<option value="Sáhara Occidental">🇪🇭 Sáhara Occidental</option>
<option value="Yemen">🇾🇪 Yemen</option>
<option value="Zambia">🇿🇲 Zambia</option>
<option value="Zimbabue">🇿🇼 Zimbabue</option>
